using System.Globalization;

using VbaNg.Compiler.Binding;
using VbaNg.Compiler.Syntax;
using VbaNg.Runtime;

namespace VbaNg.Compiler.Emit;

/// <summary>
/// Emits the C# for one bound module (ARCHITECTURE.md section 4, step 5): a static class per
/// module with a nested class per user-defined type, a nested static class per Enum, fields for
/// module variables and Static locals, and a static method per procedure. Procedures without
/// On Error, Resume, GoTo, GoSub, or labels compile to structured C#; the others compile to the
/// dispatch loop (see <see cref="Dispatch"/>).
/// </summary>
public sealed partial class CSharpEmitter
{
    private const string R = "global::VbaNg.Runtime.";
    private const string L = "global::VbaNg.Runtime.Library.";
    private const string VariantType = R + "Variant";

    private readonly BoundModule module;
    private readonly SyntaxTree tree;
    private readonly CSharpWriter writer;
    private readonly List<Diagnostic> diagnostics;
    private ProcedureSymbol? procedure;
    private List<string> before = [];
    private List<string> after = [];
    private List<string> cleanup = [];
    private int temporaries;

    /// <summary>Floating-point deferral state of the statement in progress (see IsFloating): the nesting of typed operations, whether the outermost one is stored into a Double or Single first, and whether a check is owed after that store.</summary>
    private int floatingDepth;
    private bool deferFloatingCheck;
    private bool floatingCheckDeferred;

    /// <summary>The line Erl reports at each statement index of the dispatch procedure in progress, null without numbered lines (see ErlLines).</summary>
    private int[]? erlLines;

    /// <summary>The mark of the current statement's temporaries (ARCHITECTURE.md D18), taken when the first owned value appears.</summary>
    private string? scopeMark;

    /// <summary>Set while emitting an expression that must stay one expression (a condition, a loop header); its temporaries are released inline.</summary>
    private bool inlineScope;

    private bool inlineScopeUsed;
    private readonly Stack<LoopExit> loops = new();

    /// <summary>The procedures whose address this module takes (MS-VBAL 5.6.16.8); each needs a delegate that keeps the pointer alive.</summary>
    private readonly HashSet<ProcedureSymbol> callbacks = [];
    private readonly List<string> literals = [];

    /// <summary>The With temporaries of the current procedure that own a copy of a record (a With over a function's result) rather than aliasing a variable's; the frame releases these and leaves the aliases alone.</summary>
    private readonly Dictionary<string, int> literalIndex = new(StringComparer.Ordinal);

    private CSharpEmitter(BoundModule module, List<Diagnostic> diagnostics)
    {
        this.module = module;
        this.diagnostics = diagnostics;
        tree = module.Symbol.Tree;
        writer = new CSharpWriter(tree.FilePath);
    }

    /// <summary>The C# source for a module, or null after reporting why it cannot be generated.</summary>
    public static string? Emit(BoundModule module, List<Diagnostic> diagnostics)
    {
        ArgumentNullException.ThrowIfNull(module);
        ArgumentNullException.ThrowIfNull(diagnostics);
        var emitter = new CSharpEmitter(module, diagnostics);
        var errors = diagnostics.Count(d => d.IsError);
        emitter.EmitModule();
        return diagnostics.Count(d => d.IsError) > errors ? null : emitter.writer.ToString();
    }

    private ModuleSymbol Symbol => module.Symbol;

    private void EmitModule()
    {
        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by vba-ng from " + tree.FilePath);
        writer.Line("//     Do not edit; changes are overwritten on the next build.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
        if (Symbol.Kind == ModuleKind.Document)
        {
            writer.Line($"[{R}Hosting.VbaDocumentModuleAttribute({Quote(Symbol.DocumentKind!)})]");
        }

        var isClass = Symbol.Kind == ModuleKind.Class;
        if (isClass && Symbol.IsImplemented)
        {
            EmitClassInterface();
        }

        if (isClass)
        {
            writer.HiddenLine($"[global::System.Diagnostics.DebuggerTypeProxy(typeof(global::{Symbol.ClassEmitName}.__DebugView))]");
        }

        writer.Line(isClass ? $"public sealed class {Symbol.ClassEmitName} : {ClassBases()}" : "public static class " + Symbol.EmitName);
        writer.Line("{");
        writer.Indent++;
        if (isClass)
        {
            EmitClassMembers();
        }
        else if (Symbol.Me is { } me)
        {
            writer.HiddenLine($"public static {me.Type.CSharpName} {me.EmitName};");
        }

        foreach (var length in Symbol.Records.SelectMany(r => r.Fields).Where(f => f.Type.Kind == TypeKind.FixedString || IsInlineCharsArray(f)).Select(f => f.Type.Kind == TypeKind.FixedString ? f.Type.FixedLength : f.Type.ElementType!.FixedLength).Distinct().Order())
        {
            // A fixed-length string member lies inline in its type as its UTF-16 characters at one-byte alignment, as VBA lays it out (ROADMAP.md M7 C5, C10; Memory golden): two bytes a character, so a member after a Byte starts at 1.
            writer.HiddenLine($"[global::System.Runtime.CompilerServices.InlineArray({(length * 2).ToString(CultureInfo.InvariantCulture)})]");
            writer.HiddenLine("[global::System.Diagnostics.DebuggerDisplay(\"{ToString()}\")]");
            writer.HiddenLine($"public struct {CharsType(VbaType.FixedString(length))} {{ public byte First; public override readonly string ToString() => {R}Library.Strings.FromChars(this); }}");
        }

        foreach (var field in Symbol.Records.SelectMany(r => r.Fields).Where(f => f.IsEmbeddedArray || IsInlineCharsArray(f)).DistinctBy(EmbeddedTypeName).OrderBy(EmbeddedTypeName, StringComparer.Ordinal))
        {
            EmitEmbeddedType(field);
        }

        foreach (var record in Symbol.Records)
        {
            EmitRecord(record);
        }

        foreach (var enumeration in Symbol.Enums)
        {
            EmitEnum(enumeration);
        }

        // A class module's variables and Static locals live in each instance (MS-VBAL 5.2.3.1), in its block (ROADMAP.md M7 E4).
        var shared = isClass ? string.Empty : "static ";
        EmitInstanceBlock();
        if (isClass)
        {
            EmitDebugView();
        }

        foreach (var variable in Symbol.Variables)
        {
            var access = SlotAccess(variable, variable.IsPublic);
            writer.MappedLine(Line(variable.Syntax!), InInstanceBlock(variable)
                ? $"{access} ref {StorageType(variable)} {variable.EmitName} => ref {R}InstanceBlocks.Of(this).{variable.EmitName};"
                : $"{access} {shared}{StorageType(variable)} {variable.EmitName} = {InitialValue(variable)};");
            if (variable.EventInterface is { } source)
            {
                // A WithEvents variable of a library type: the events its handlers take, and the advisory Set holds (MS-VBAL 5.2.3.1.4).
                var events = Symbol.Procedures.Where(p => p.EventVariable == variable)
                    .Select(p => $"({source.FindMember(p.EventName!, Runtime.TypeLibraries.ComMemberKind.Method)!.DispId.ToString(CultureInfo.InvariantCulture)}, {Quote(p.EventName!)})");
                writer.HiddenLine($"private static readonly {R}ComEventInterface {EventsName(variable)} = new(new global::System.Guid({Quote(source.Guid.ToString("D"))}), {Quote(source.Name)}, new (int, string)[] {{ {string.Join(", ", events)} }});");
                writer.HiddenLine($"private {shared}global::System.IDisposable? {AdvisoryName(variable)};");
            }
        }

        foreach (var local in Symbol.StaticLocals)
        {
            writer.HiddenLine(InInstanceBlock(local)
                ? $"private ref {StorageType(local)} {local.EmitName} => ref {R}InstanceBlocks.Of(this).{local.EmitName};"
                : $"private {shared}{StorageType(local)} {local.EmitName} = {InitialValue(local)};");
        }

        if (!isClass && Symbol.EventSources.Count > 0)
        {
            // A document module's WithEvents handlers are static, so a nested object stands in for the class instance as the sink.
            writer.HiddenLine("private static readonly __EventSink __events = new();");
            writer.HiddenLine($"private sealed class __EventSink : {R}IVbaEventSink");
            writer.Open();
            EmitEventSink();
            writer.Close();
        }

        if (Symbol.Variables.Count > 0 || Symbol.StaticLocals.Count > 0)
        {
            writer.Hidden();
            writer.Line();
        }

        EmitReset();
        EmitExternals();
        foreach (var bound in module.Procedures)
        {
            EmitProcedure(bound);
        }

        if (Symbol.Kind is ModuleKind.Standard or ModuleKind.Document)
        {
            EmitRunTable();
        }

        EmitAppObjectFields();
        EmitCallbacks();
        EmitLiterals();
        writer.Indent--;
        writer.Hidden();
        writer.Line("}");
    }

    /// <summary>
    /// A user-defined type becomes a struct with a field per member (MS-VBAL 5.2.3.3), copied by
    /// value: Copy duplicates what it owns for an assignment, ReleaseReferences drops it when its
    /// storage goes, and Fresh is the value the arrays that hold it start from (ROADMAP.md M7 C3).
    /// </summary>
    /// <summary>The inline storage of a fixed-size array member (ROADMAP.md M7 C6): its elements one after another as VBA lays them out, with the element type and bounds the runtime reads.</summary>
    private void EmitEmbeddedType(VariableSymbol field)
    {
        var name = EmbeddedTypeName(field);
        var bounds = field.Bounds!;
        var count = bounds.Aggregate(1L, (n, b) => n * ((long)b.Upper - b.Lower + 1));
        var element = field.Type.ElementType!;
        var text = $"{(element.IsRecord ? element.Record!.Name : element.Kind == TypeKind.FixedString ? "String * " + element.FixedLength.ToString(CultureInfo.InvariantCulture) : element.VarType.ToString())}({string.Join(", ", bounds.Select(b => $"{b.Lower.ToString(CultureInfo.InvariantCulture)} To {b.Upper.ToString(CultureInfo.InvariantCulture)}"))})";
        writer.HiddenLine($"[global::System.Runtime.CompilerServices.InlineArray({count.ToString(CultureInfo.InvariantCulture)})]");
        writer.HiddenLine($"[global::System.Diagnostics.DebuggerDisplay({Quote(text)})]");
        writer.HiddenLine($"[global::System.Diagnostics.DebuggerTypeProxy(typeof({R}{(element.Kind == TypeKind.FixedString ? "EmbeddedCharsView" : "EmbeddedArrayView")}<{name}>))]");
        writer.HiddenLine($"{(element.Record is { IsPublic: false } ? "internal" : "public")} struct {name} : {R}IEmbeddedArray");
        writer.Open();
        writer.HiddenLine($"public {EmbeddedElementType(element)} First;");
        writer.HiddenLine($"public static {R}VarType ElementType => {VarTypeName(element)};");
        writer.HiddenLine($"public static int[] Bounds => [{string.Join(", ", bounds.SelectMany(b => new[] { b.Lower, b.Upper }).Select(n => n.ToString(CultureInfo.InvariantCulture)))}];");
        writer.Close();
    }

    /// <summary>A fixed-size array member whose elements hold something a copy must own and a release must free: strings, objects, Variants, records.</summary>
    private static bool EmbeddedHoldsReferences(VariableSymbol field) =>
        field.Type.ElementType is { } element && (element.IsVariableString || element.IsObject || element.IsVariant || element.IsRecord);

    private void EmitRecord(RecordSymbol record)
    {
        var access = record.IsPublic ? "public" : "internal";
        writer.MappedLine(Line(record.Syntax), $"{access} struct {record.EmitName} : {R}IVbaRecord<{record.EmitName}>");
        writer.Open();
        foreach (var field in record.Fields)
        {
            if (field.Type.Kind == TypeKind.FixedString)
            {
                // Put and Get lay a String * n out as n ANSI bytes (MS-VBAL 5.4.5.9); the attribute carries n to the runtime.
                writer.HiddenLine($"[{L}VbaField({R}VarType.String, {field.Type.FixedLength.ToString(CultureInfo.InvariantCulture)})]");
            }
            else if (IsInlineCharsArray(field))
            {
                // Put, Get, LenB, and LSet lay out each element of a fixed-length string array as its n characters (ROADMAP.md M7 C10).
                writer.HiddenLine($"[{L}VbaField({R}VarType.String, {field.Type.ElementType!.FixedLength.ToString(CultureInfo.InvariantCulture)})]");
            }
            else if (IsDynamicArrayMember(field))
            {
                // The file statements, Len, LenB, and LSet reach a dynamic array member through a view of this element type (ROADMAP.md M7 C8).
                writer.HiddenLine($"[{L}VbaField({VarTypeName(field.Type.ElementType!)})]");
            }

            writer.MappedLine(Line(field.Syntax!), $"public {StorageType(field)} {field.EmitName} = {InitialValue(field)};");
        }

        // The field initializers run in the parameterless constructor, so new() is the fresh value; default never is.
        writer.HiddenLine($"public {record.EmitName}()");
        writer.Open();
        writer.Close();
        writer.HiddenLine($"public static {record.EmitName} Fresh() => new();");
        writer.HiddenLine($"public readonly {record.EmitName} Copy()");
        writer.Open();
        writer.HiddenLine("var copy = this;");
        foreach (var field in record.Fields)
        {
            // The copy's object fields hold references of their own, its strings, arrays, and nested records are copies (ARCHITECTURE.md D18, D20); its scalars came with the struct.
            var value = field.IsEmbeddedArray || IsInlineCharsArray(field) ? null
                : IsDynamicArrayMember(field) ? $"{field.EmitName}.View({VarTypeName(field.Type.ElementType!)}).Clone()"
                : field.Type.IsArray ? $"{field.EmitName}.Clone()"
                : field.Type.IsRecord ? $"{field.EmitName}.Copy()"
                : field.Type.IsVariant || field.Type.IsVariableString ? $"{R}ObjectRefs.Own({field.EmitName})"
                : null;
            if (value is not null)
            {
                writer.HiddenLine($"copy.{field.EmitName} = {value};");
            }
        }

        foreach (var field in record.Fields.Where(f => f.Type.IsObject))
        {
            writer.HiddenLine($"{R}ObjectRefs.Retain(copy.{field.EmitName});");
        }

        foreach (var field in record.Fields.Where(f => f.IsEmbeddedArray && EmbeddedHoldsReferences(f)))
        {
            // The copy's elements came across byte for byte: they take their own strings, references, and Variants (ROADMAP.md M7 C6).
            writer.HiddenLine($"{R}VbaArray.OwnEmbedded(ref copy.{field.EmitName});");
        }

        writer.HiddenLine("return copy;");
        writer.Close();
        writer.HiddenLine("public void ReleaseReferences()");
        writer.Open();
        foreach (var field in record.Fields)
        {
            if (field.Type.IsRecord)
            {
                writer.HiddenLine($"{field.EmitName}.ReleaseReferences();");
            }
            else if (field.IsEmbeddedArray)
            {
                if (EmbeddedHoldsReferences(field))
                {
                    writer.HiddenLine($"{R}VbaArray.ReleaseEmbedded(ref {field.EmitName});");
                }
            }
            else if (IsDynamicArrayMember(field))
            {
                writer.HiddenLine($"{R}VbaArrayMember.Release(ref {field.EmitName}, {VarTypeName(field.Type.ElementType!)});");
            }
            else if (field.Type.IsArray && !IsInlineCharsArray(field))
            {
                writer.HiddenLine($"{R}ObjectRefs.Release(ref {field.EmitName});");
            }
            else if (field.Type.IsObject || field.Type.IsVariant || field.Type.IsVariableString)
            {
                writer.HiddenLine($"{R}ObjectRefs.Release(ref {field.EmitName});");
            }
        }

        writer.Close();
        writer.Close();
        writer.Hidden();
        writer.Line();
    }

    private void EmitEnum(EnumSymbol enumeration)
    {
        var access = enumeration.IsPublic ? "public" : "internal";
        writer.MappedLine(Line(enumeration.Syntax), $"{access} static class {enumeration.EmitName}");
        writer.Open();
        foreach (var member in enumeration.Members)
        {
            writer.HiddenLine($"public const int {CSharpNames.Identifier(member.Name)} = {member.Value.AsInt32().ToString(CultureInfo.InvariantCulture)};");
        }

        writer.Close();
        writer.Hidden();
        writer.Line();
    }

    private void EmitProcedure(BoundProcedure bound)
    {
        procedure = bound.Symbol;
        temporaries = 0;
        loops.Clear();
        var symbol = bound.Symbol;
        var access = symbol.IsPublic ? "public" : "internal";
        var returnType = symbol.ReturnType?.CSharpName ?? "void";
        var parameters = string.Join(", ", symbol.Parameters.Select(ParameterDeclaration));

        if (symbol.IsTest)
        {
            writer.HiddenLine($"[{R}Hosting.VbaTestAttribute]");
        }

        if (symbol.EventSource is not null && symbol.EventVariable is null)
        {
            // The host connects a document module's own and its controls' events; WithEvents variables connect through the sink.
            writer.HiddenLine($"[{R}Hosting.VbaEventHandlerAttribute({Quote(symbol.EventSource)}, {Quote(symbol.EventName!)})]");
        }

        if (symbol.Kind is ProcedureKind.Sub or ProcedureKind.Function && symbol.EmitName.TrimStart('@') != symbol.Name)
        {
            // The host resolves Application.Run and test names by VBA name (VbaNames.Of).
            writer.HiddenLine($"[{R}VbaNameAttribute({Quote(symbol.Name)})]");
        }

        var shared = Symbol.Kind == ModuleKind.Class ? string.Empty : "static ";
        writer.MappedLine(Line(symbol.Syntax), $"{access} {shared}{returnType} {symbol.EmitName}({parameters})");
        writer.Open();

        foreach (var local in bound.Locals)
        {
            if (local.IsAlias)
            {
                // A With over a record's storage: a ref the With statement points at it (MS-VBAL 5.4.2.7), scoped so it may point at a local.
                writer.HiddenLine($"scoped ref {local.Type.CSharpName} {local.EmitName} = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<{local.Type.CSharpName}>();");
                continue;
            }

            writer.HiddenLine($"{local.EmitType ?? StorageType(local)} {local.EmitName} = {local.EmitDefault ?? InitialValue(local)};");
        }

        if (symbol.Result is { } result)
        {
            writer.HiddenLine($"{StorageType(result)} {result.EmitName} = {InitialValue(result)};");
        }

        // The object references the frame holds go when it ends, in declaration order (ARCHITECTURE.md D18). Every
        // procedure takes a frame, because any statement may create a string the statement owns (D20).
        // A For Each enumerator goes first, so the array it locks is unlocked before its variable is destroyed (M7 C4).
        var released = bound.Locals.Where(NeedsRelease).OrderBy(v => v.EmitType is null ? 1 : 0).Concat(symbol.Parameters.Where(p => p.IsByVal && NeedsRelease(p))).ToList();
        foreach (var parameter in symbol.Parameters.Where(p => p.IsByVal && NeedsRelease(p)))
        {
            // A ByVal parameter owns its value for the length of the call: a reference of its own, or a copy of a string.
            writer.HiddenLine(parameter.Type.IsVariant || parameter.Type.IsVariableString
                ? $"{parameter.EmitName} = {R}ObjectRefs.Own({parameter.EmitName});"
                : IsObjectSlot(parameter) ? $"{SlotType(parameter.Type)} {StorageName(parameter)} = {R}ObjectRefs.Holding<{ClassName(parameter.Type)}>({parameter.EmitName});"
                : $"{R}ObjectRefs.Retain({parameter.EmitName});");
        }

        writer.HiddenLine($"var __scope = {R}ObjectRefs.Mark();");
        writer.HiddenLine("try");
        writer.Open();

        if (bound.UsesDispatch)
        {
            EmitDispatch(bound);
        }
        else
        {
            EmitBlock(bound.Body);
            writer.MappedLine(Line(symbol.Syntax.EndStatement), ReturnCode());
        }

        writer.Close();
        writer.HiddenLine("finally");
        writer.Open();
        writer.HiddenLine($"{R}ObjectRefs.ReleaseTo(__scope);");
        foreach (var variable in released)
        {
            writer.HiddenLine(ReleaseCode(variable, StorageName(variable)));
        }

        writer.Close();
        writer.Close();
        writer.Hidden();
        writer.Line();
        procedure = null;
    }

    /// <summary>
    /// The store that starts a With block (MS-VBAL 5.4.2.7): a record variable, field, or element
    /// is aliased by a ref, so writes through the block reach it; a record value (a function's
    /// result, a temporary of its statement) is copied into the temporary, which owns the copy
    /// until the frame ends. An object is held by a reference the block drops at End With
    /// (Classes golden).
    /// </summary>
    private string WithStore(BoundWith with)
    {
        var temporary = with.Temporary;
        if (temporary.IsAlias)
        {
            return $"{temporary.EmitName} = ref {EmitExpression(with.Target).Code};";
        }

        if (temporary.Type.IsRecord)
        {
            return $"{R}ObjectRefs.AssignRecord(ref {temporary.EmitName}, {Convert(EmitExpression(with.Target), temporary.Type)});";
        }

        return Store(new BoundVariable(with.Syntax, temporary), EmitExpression(with.Target)) + ";";
    }

    /// <summary>Leaving a procedure: a Function or Property Get hands the reference its result holds to the caller's statement (ARCHITECTURE.md D18).</summary>
    private string ReturnCode()
    {
        if (procedure?.Result is not { } result)
        {
            return "return;";
        }

        if (!NeedsRelease(result))
        {
            return $"return {result.EmitName};";
        }

        return result.Type.IsRecord ? $"return {R}ObjectRefs.TransferRecord(ref {result.EmitName});" : $"return {R}ObjectRefs.Transfer(ref {result.EmitName});";
    }

    /// <summary>A value the current statement owns: created here, released when the statement ends.</summary>
    private string Owned(string code)
    {
        OpenScope();
        return $"{R}ObjectRefs.Owned({code})";
    }

    /// <summary>The statement takes a scope because a call may hand it a reference to release.</summary>
    private void OpenScope()
    {
        if (inlineScope)
        {
            inlineScopeUsed = true;
            return;
        }

        if (scopeMark is null)
        {
            scopeMark = "__scope" + (++temporaries).ToString(CultureInfo.InvariantCulture);
            before.Insert(0, $"var {scopeMark} = {R}ObjectRefs.Mark();");
            after.Add($"{R}ObjectRefs.ReleaseTo({scopeMark});");
        }
    }

    /// <summary>Emits an expression that has to stay one expression, releasing any temporaries it creates as it yields its value.</summary>
    private string Inline(Func<string> emit)
    {
        var outerScope = inlineScope;
        var outerUsed = inlineScopeUsed;
        inlineScope = true;
        inlineScopeUsed = false;
        try
        {
            var code = emit();
            return inlineScopeUsed ? $"{R}ObjectRefs.After({R}ObjectRefs.Mark(), {code})" : code;
        }
        finally
        {
            inlineScope = outerScope;
            inlineScopeUsed = outerUsed;
        }
    }

    private static string ParameterDeclaration(ParameterSymbol parameter)
    {
        var modifier = parameter.EmitByRef ? "ref " : string.Empty;
        var type = ReferenceEquals(parameter.Type, VbaType.Any) && parameter.IsByVal ? "nint" : parameter is { IsExternal: true, Type.IsRecord: true } ? "byte" : parameter is { IsExternal: true, IsByVal: false } && ReferenceEquals(parameter.Type, VbaType.Boolean) ? "short" : parameter.EmitByRef && IsObjectSlot(parameter) ? SlotType(parameter.Type) : parameter.Type.CSharpName;
        return $"{modifier}{type} {parameter.EmitName}";
    }

    /// <summary>The initial value of a variable of a declared type (MS-VBAL 5.2.3.1: 0, "", False, Nothing, Empty, or a fresh array or record).</summary>
    private static string DefaultValue(VariableSymbol variable)
    {
        var type = variable.Type;
        if (type.IsArray)
        {
            var element = type.ElementType!;
            if (element.IsRecord && variable.Bounds is { } recordBounds)
            {
                return $"{R}VbaArray.CreateRecords<{element.CSharpName}>({Bounds(recordBounds)}, fixedSize: true)";
            }

            if (element.Kind == TypeKind.FixedString && variable.Bounds is { } fixedBounds)
            {
                // A fixed-length string array's elements start as n Chr(0)s, as a String * n does (Arrays golden).
                return $"{R}VbaArray.FixedStrings({R}VbaArray.Create({VarTypeName(element)}, {Bounds(fixedBounds)}, fixedSize: true), {element.FixedLength.ToString(CultureInfo.InvariantCulture)})";
            }

            return variable.Bounds is { } bounds
                ? $"{R}VbaArray.Create({VarTypeName(element)}, {Bounds(bounds)}, fixedSize: true)"
                : $"{R}VbaArray.Unallocated({VarTypeName(element)})";
        }

        return DefaultValue(type);
    }

    private static string DefaultValue(VbaType type)
    {
        if (type.IsRecord)
        {
            return $"new {type.CSharpName}()";
        }

        if (type.Kind == TypeKind.FixedString)
        {
            return $"new string('\\0', {type.FixedLength.ToString(CultureInfo.InvariantCulture)})";
        }

        return type.VarType switch
        {
            VarType.Integer => "0",
            VarType.Long => "0",
            VarType.LongLong => "0L",
            VarType.Single => "0f",
            VarType.Double => "0d",
            VarType.Byte => "0",
            VarType.Boolean => "false",
            VarType.String => R + "VbaString.Null",
            VarType.Currency => R + "Currency.Zero",
            VarType.Date => R + "VbaDate.Zero",
            VarType.Variant => VariantType + ".Empty",
            VarType.Decimal => "0m",
            _ => "null",
        };
    }

    private static string Bounds((int Lower, int Upper)[] bounds) =>
        "[" + string.Join(", ", bounds.Select(b => $"({b.Lower.ToString(CultureInfo.InvariantCulture)}, {b.Upper.ToString(CultureInfo.InvariantCulture)})")) + "]";

    private static string VarTypeName(VbaType type) => R + "VarType." + type.VarType;

    private int Line(SyntaxNode node) => tree.GetLinePosition(node.FirstToken()!).Line;

    private static string Quote(string text) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(text, quote: true);

    private void Report(SyntaxNode node, string message)
    {
        var (line, column) = tree.GetLinePosition(node.FirstToken()!);
        diagnostics.Add(new Diagnostic(DiagnosticIds.NotSupported, DiagnosticSeverity.Error, message, tree.FilePath, line, column));
    }

    // Structured statements.

    private void EmitBlock(BoundBlock block)
    {
        foreach (var statement in block.Statements)
        {
            EmitStatement(statement);
        }
    }

    private void EmitStatement(BoundStatement statement)
    {
        switch (statement)
        {
            case BoundNop or BoundLocalDeclaration or BoundLabel:
                return;
            case BoundBlock block:
                EmitBlock(block);
                return;
            case BoundIf ifStatement:
                EmitIf(ifStatement);
                return;
            case BoundSelect select:
                EmitSelect(select);
                return;
            case BoundFor forLoop:
                EmitFor(forLoop);
                return;
            case BoundForEach forEach:
                EmitForEach(forEach);
                return;
            case BoundDoLoop doLoop:
                EmitDoLoop(doLoop);
                return;
            case BoundWith with:
                EmitSimple(with, WithStore(with));
                EmitBlock(with.Body);
                if (Counted(with.Temporary.Type))
                {
                    // The reference the With block holds goes at End With (Classes golden); a record temporary aliases its record and is left alone.
                    writer.MappedLine(Line(with.Syntax), ReleaseCode(with.Temporary, with.Temporary.EmitName));
                }

                return;
            case BoundExit { Kind: ExitKind.Procedure } exit:
                writer.MappedLine(Line(exit.Syntax), ReturnCode());
                return;
            case BoundExit exit:
                {
                    var target = loops.First(l => l.Kind == exit.Kind);
                    target.Used = true;
                    writer.MappedLine(Line(exit.Syntax), $"goto {target.Label};");
                    return;
                }

            default:
                EmitSimpleStatement(statement);
                return;
        }
    }

    /// <summary>Emits a statement that maps to one line, with the copy-back and initialization statements its expressions need around it.</summary>
    private void EmitSimple(BoundStatement statement, string code) => EmitSimple(Line(statement.Syntax), code);

    private void EmitSimple(int line, string code)
    {
        if (procedure is not null && !code.StartsWith("else", StringComparison.Ordinal))
        {
            // The strings and objects the previous statement created as temporaries go before this one starts
            // (ARCHITECTURE.md D18, D20); an else-if header stays glued to the block before it.
            writer.HiddenLine($"{R}ObjectRefs.ReleaseTo(__scope);");
        }

        writer.MapLine(line);
        var needsBlock = before.Count > 0 || after.Count > 0 || cleanup.Count > 0;
        if (needsBlock)
        {
            writer.Line("{");
            writer.Indent++;
            foreach (var pre in before)
            {
                writer.Line(pre);
            }
        }

        // A hidden temporary that owns a value is released whether the statement completes or raises,
        // so an error skipped by Resume Next leaks nothing (D20); the copy-backs run only on completion.
        if (cleanup.Count > 0)
        {
            writer.Line("try");
            writer.Line("{");
            writer.Indent++;
        }

        writer.Line(code);
        foreach (var post in after)
        {
            writer.Line(post);
        }

        if (cleanup.Count > 0)
        {
            writer.Indent--;
            writer.Line("}");
            writer.Line("finally");
            writer.Line("{");
            writer.Indent++;
            foreach (var release in cleanup)
            {
                writer.Line(release);
            }

            writer.Indent--;
            writer.Line("}");
        }

        if (needsBlock)
        {
            writer.Indent--;
            writer.Line("}");
        }

        before = [];
        after = [];
        cleanup = [];
        scopeMark = null;
    }

    private void EmitSimpleStatement(BoundStatement statement)
    {
        var code = SimpleStatementCode(statement);
        if (code is not null)
        {
            EmitSimple(statement, code);
        }
    }

    /// <summary>The C# for a statement that is not a block, a loop, a branch, or a jump; null when nothing is emitted.</summary>
    private string? SimpleStatementCode(BoundStatement statement)
    {
        switch (statement)
        {
            case BoundAssignment assignment:
                return Assignment(assignment);
            case BoundExpressionStatement call:
                return CallStatement(call.Expression);
            case BoundReDim redim:
                return ReDim(redim);
            case BoundErase erase:
                return string.Join(" ", erase.Targets.Select(Erase));
            case BoundMidAssignment mid:
                {
                    var target = EmitExpression(mid.Target);
                    var length = mid.Length is null ? "null" : Convert(EmitExpression(mid.Length), VbaType.Long);
                    var start = Convert(EmitExpression(mid.Start), VbaType.Long);
                    if (target.Type.Kind == TypeKind.FixedString)
                    {
                        // A fixed-length string is still a .NET string: the replaced text is stored back.
                        var replaced = $"{L}Strings.MidAssign({target.Code}, {start}, {length}, {Convert(EmitExpression(mid.Value), VbaType.String)})";
                        return Store(mid.Target, new Emitted(replaced, target.Type)) + ";";
                    }

                    // A String variable, or a Variant holding one, is written in place (ARCHITECTURE.md D20).
                    var text = target.Type.IsVariableString ? target.Code : $"{R}Coerce.ToText({Convert(target, VbaType.Variant)})";
                    return $"{L}Strings.MidAssign({text}, {start}, {length}, {Convert(EmitExpression(mid.Value), VbaType.String)});";
                }

            case BoundLSet lset:
                {
                    if (lset.Target.Type.IsRecord)
                    {
                        return $"{L}RecordImage.LSet(ref {EmitExpression(lset.Target).Code}, {EmitExpression(lset.Value).Code});";
                    }

                    var current = EmitExpression(lset.Target);
                    if (current.Type.Kind == TypeKind.FixedString)
                    {
                        var fixedResult = $"{L}Strings.{(lset.IsRSet ? "RSet" : "LSet")}({current.Code}, {Convert(EmitExpression(lset.Value), VbaType.String)})";
                        return Store(lset.Target, new Emitted(fixedResult, current.Type)) + ";";
                    }

                    var text = current.Type.IsVariableString ? current.Code : $"{R}Coerce.ToText({Convert(current, VbaType.Variant)})";
                    var justified = $"{L}Strings.{(lset.IsRSet ? "RSet" : "LSet")}({text}, {Convert(EmitExpression(lset.Value), VbaType.String)})";
                    return Store(lset.Target, new Emitted(justified, VbaType.String)) + ";";
                }

            case BoundErrorStatement error:
                return $"throw {R}Err.Current.Raise({Convert(EmitExpression(error.Number), VbaType.Variant)});";
            case BoundEnd:
                return EndCode();
            case BoundStop:
                return R + "Debug.Stop();";
            case BoundDebugPrint print:
                return DebugPrint(print);
            case BoundRaiseEvent raise:
                return RaiseEvent(raise);
            case BoundOpen or BoundFileStatement or BoundFileOutput or BoundFileInput or BoundFileRecord:
                return FileStatement(statement);
            case BoundOnError or BoundResume or BoundGoTo or BoundGoSub or BoundReturn or BoundOnGoTo:
                Report(statement.Syntax, "Statement needs the dispatch loop; this is a compiler bug.");
                return null;
            default:
                Report(statement.Syntax, $"{statement.GetType().Name} is not supported yet.");
                return null;
        }
    }

    private string Assignment(BoundAssignment assignment)
    {
        if (assignment.Target is BoundMember { Target: BoundCall letCall } property && property.Type is not null && letCall.Procedure.Kind is ProcedureKind.PropertyLet or ProcedureKind.PropertySet)
        {
            // x = value where x is a Property: Let_x(indexes, value) (MS-VBAL 5.3.1.4).
            var parameter = letCall.Procedure.Parameters[^1];
            var value = Convert(EmitExpression(assignment.Value), parameter.Type);
            if (parameter.EmitByRef)
            {
                // The value parameter is ByRef unless declared ByVal: the assigned value reaches it as a temporary the accessor may change (Procedures golden).
                var temporary = NewTemporary();
                before.Add($"var {temporary} = {RefValue(value, parameter)};");
                ReleaseAfter(temporary, parameter.Type, IsObjectSlot(parameter));
                value = "ref " + temporary;
            }

            return $"{CallCode(letCall, value)};";
        }

        // A Double or Single variable takes a typed operation's IEEE result before its division by zero or overflow is raised (docs/vba-quirks.md).
        deferFloatingCheck = !assignment.IsSet && IsFloatingType(assignment.Target.Type) && assignment.Target is BoundVariable or BoundField or BoundElement && IsFloating(assignment.Value);
        var copyBacks = after.Count;
        var emitted = EmitExpression(assignment.Value);
        var copiedBack = after.Count - copyBacks;
        deferFloatingCheck = false;
        if (floatingCheckDeferred)
        {
            floatingCheckDeferred = false;
            after.Add($"{R}Operators.CheckFloating();");
        }

        if (assignment.IsSet && assignment.Target.Type.IsVariant)
        {
            emitted = emitted.Type.IsVariant
                ? new Emitted($"{VariantType}.FromObject({R}Coerce.ToObject<object>({emitted.Code}))", VbaType.Variant)
                : new Emitted($"{VariantType}.FromObject({emitted.Code})", VbaType.Variant);
        }

        var prefix = string.Empty;
        var added = after.GetRange(copyBacks, copiedBack);
        var scopeRelease = scopeMark is null ? null : $"{R}ObjectRefs.ReleaseTo({scopeMark});";
        var backs = added.Where(line => line != scopeRelease).ToList();
        if (backs.Count > 0)
        {
            // A ByRef argument goes back when its call returns (MS-VBAL 5.6.13.1), before the statement stores the
            // call's result: x = F(x) keeps what F returned (Procedures golden). The statement's scope still ends after the store.
            var result = NewTemporary();
            prefix = $"var {result} = {emitted.Code}; " + string.Join(" ", backs) + " ";
            after.RemoveRange(copyBacks, copiedBack);
            after.InsertRange(copyBacks, added.Where(line => line == scopeRelease));
            emitted = new Emitted(result, emitted.Type);
        }

        storeIsSet = assignment.IsSet;
        storeIsLet = !assignment.IsSet;
        try
        {
            return prefix + Store(assignment.Target, emitted) + ";";
        }
        finally
        {
            storeIsSet = false;
            storeIsLet = false;
        }
    }

    private string CallStatement(BoundExpression expression)
    {
        switch (expression)
        {
            case BoundMember { Member: "Raise", Target.Type.Kind: TypeKind.Class } raise when ReferenceEquals(raise.Target.Type, VbaType.ErrObject):
                return $"throw {ErrTarget(raise.Target)}.Raise({string.Join(", ", raise.Arguments.Select(a => Convert(EmitExpression(a), VbaType.Variant)))});";
            case BoundMember { Target.Type: var type } member when type.IsVariant || type.IsGenericObject:
                return $"{R}LateBound.Call({Convert(EmitExpression(member.Target), VbaType.Variant)}, {Quote(member.Member)}, {Arguments(member.Arguments)}{Names(member)});";
            case BoundIntrinsicCall { Intrinsic.IsSub: false } call:
                return $"_ = {EmitExpression(call).Code};";
            case BoundLiteral:
                return null!;
            default:
                return EmitExpression(expression).Code + ";";
        }
    }

    private string ReDim(BoundReDim redim)
    {
        var bounds = "[" + string.Join(", ", redim.Bounds.Select(b =>
            $"({(b.Lower is null ? Symbol.Options.Base.ToString(CultureInfo.InvariantCulture) : Convert(EmitExpression(b.Lower), VbaType.Long))}, {Convert(EmitExpression(b.Upper), VbaType.Long)})")) + "]";
        var preserve = redim.Preserve ? "true" : "false";
        if (redim.Target.Type.IsArray)
        {
            if (redim.Target.Type.ElementType is { Kind: TypeKind.FixedString } fixedString)
            {
                // The elements a ReDim makes start as n Chr(0)s (Arrays golden).
                var reference = ArrayReference(redim.Target);
                return $"{R}VbaArray.ReDimDeclared(ref {reference}, {bounds}, preserve: {preserve}); {R}VbaArray.FixedStrings({reference}, {fixedString.FixedLength.ToString(CultureInfo.InvariantCulture)});";
            }

            return redim.Target.Type.ElementType!.IsRecord
                ? $"{R}VbaArray.ReDimRecords<{redim.Target.Type.ElementType!.CSharpName}>(ref {ArrayReference(redim.Target)}, {bounds}, preserve: {preserve});"
                : $"{R}VbaArray.ReDimDeclared(ref {ArrayReference(redim.Target)}, {bounds}, preserve: {preserve});";
        }

        return WithReference(redim.Target, reference => $"{R}VbaArray.ReDimVariant(ref {reference}, {VarTypeName(redim.ElementType)}, {bounds}, preserve: {preserve});");
    }

    private string Erase(BoundExpression target)
    {
        if (target is BoundField { Field: var chars } inline && IsInlineCharsArray(chars))
        {
            // Erase on a fixed-size array of fixed-length strings zeroes the characters in place (ROADMAP.md M7 C10; Memory golden).
            return $"{FieldOwner(inline)}.{chars.EmitName} = default;";
        }

        if (target.Type.ElementType is { Kind: TypeKind.FixedString } fixedString)
        {
            // Erase on a fixed-size array of fixed-length strings leaves each element n Chr(0)s; a dynamic one it deallocates (Arrays golden).
            var reference = ArrayReference(target);
            return $"{R}VbaArray.Erase(ref {reference}); {R}VbaArray.FixedStrings({reference}, {fixedString.FixedLength.ToString(CultureInfo.InvariantCulture)});";
        }

        if (target.Type.IsArray)
        {
            return $"{R}VbaArray.Erase(ref {ArrayReference(target)});";
        }

        return WithReference(target, reference => $"{R}VbaArray.Erase(ref {reference});");
    }

    /// <summary>Runs code that needs a C# reference to a Variant storage location, copying an element or late member in and out when a ref is impossible.</summary>
    private string WithReference(BoundExpression target, Func<string, string> code)
    {
        if (target is BoundVariable { Variable.IsNew: false } or BoundField)
        {
            return code(EmitExpression(target).Code);
        }

        var temporary = NewTemporary();
        before.Add($"var {temporary} = {Own(Convert(EmitExpression(target), VbaType.Variant), VbaType.Variant)};");
        after.Add(Store(target, new Emitted(temporary, VbaType.Variant)) + ";");
        ReleaseAfter(temporary, VbaType.Variant);
        return code(temporary);
    }

    /// <summary>A hidden Variant or String temporary owns its value, a string as a copy, since the callee it is passed to by reference may reassign it (ARCHITECTURE.md D20).</summary>
    private static string Own(string value, VbaType type) => type.IsVariant || type.IsVariableString ? $"{R}ObjectRefs.Own({value})" : type.IsArray ? value + ".Clone()" : value;

    /// <summary>The hidden temporary's value goes when its statement ends, an error raised by the call included.</summary>
    private void ReleaseAfter(string temporary, VbaType type, bool objectSlot = false)
    {
        if (objectSlot || type.IsVariant || type.IsVariableString || type.IsArray)
        {
            cleanup.Add($"{R}ObjectRefs.Release(ref {temporary});");
        }
        else if (type.IsRecord)
        {
            // A record temporary, the copy a ByRef parameter works on, drops what the copy owns (D18).
            cleanup.Add($"{temporary}.ReleaseReferences();");
        }
    }

    private string DebugPrint(BoundDebugPrint print) => $"{R}Debug.Print({PrintListCode(print.Items)}, endLine: {Bool(EndsLine(print.Items))});";

    private void EmitIf(BoundIf ifStatement)
    {
        var first = true;
        var nested = 0;
        foreach (var branch in ifStatement.Branches)
        {
            var condition = Condition(branch.Condition);
            EmitBranchHeader(ifStatement, condition, first, ref nested);
            first = false;
            writer.Open();
            EmitBlock(branch.Body);
            writer.Close();
        }

        if (ifStatement.ElseBody is not null)
        {
            writer.HiddenLine("else");
            writer.Open();
            EmitBlock(ifStatement.ElseBody);
            writer.Close();
        }

        CloseBranchBlocks(nested);
    }

    /// <summary>
    /// The header of one branch of an If or a Select Case: "if (condition)", or "else if" after the
    /// first. A condition whose calls needed temporaries (a copy for a ByRef parameter, a String
    /// released after the statement) is evaluated into a flag first, since the try and copy-backs
    /// around it cannot stand between the header and its block; a later branch then opens an else
    /// block of its own, which <paramref name="nested"/> counts for <see cref="CloseBranchBlocks"/>.
    /// </summary>
    private void EmitBranchHeader(BoundStatement statement, string condition, bool first, ref int nested)
    {
        if (before.Count == 0 && after.Count == 0 && cleanup.Count == 0)
        {
            EmitSimple(statement, $"{(first ? "if" : "else if")} ({condition})");
            return;
        }

        if (!first)
        {
            writer.HiddenLine("else");
            writer.Open();
            nested++;
        }

        var flag = "__c" + (++temporaries).ToString(CultureInfo.InvariantCulture);
        writer.HiddenLine($"bool {flag};");
        EmitSimple(statement, $"{flag} = {condition};");
        writer.HiddenLine($"if ({flag})");
    }

    private void CloseBranchBlocks(int nested)
    {
        for (var i = 0; i < nested; i++)
        {
            writer.Close();
        }
    }

    private string Condition(BoundExpression condition) => Inline(() =>
    {
        var emitted = EmitExpression(condition);
        return emitted.Type.VarType == VarType.Boolean && emitted.Type.Kind == TypeKind.Builtin
            ? emitted.Code
            : $"{R}Coerce.ToCondition({Convert(emitted, VbaType.Variant)})";
    });

    private void EmitSelect(BoundSelect select)
    {
        // The selector slot owns its value (a string is copied) and the frame releases it, as for any Variant local (D20).
        EmitSimple(select, Store(new BoundVariable(select.Syntax, select.Selector), EmitExpression(select.Value)) + ";");
        var first = true;
        var nested = 0;
        foreach (var block in select.Cases)
        {
            var test = string.Join(" || ", block.Clauses.Select(clause => CaseTest(select, select.Selector, clause)));
            EmitBranchHeader(block.Body, test, first, ref nested);
            first = false;
            writer.Open();
            EmitBlock(block.Body);
            writer.Close();
        }

        if (select.ElseBody is not null)
        {
            if (first)
            {
                EmitBlock(select.ElseBody);
            }
            else
            {
                writer.HiddenLine("else");
                writer.Open();
                EmitBlock(select.ElseBody);
                writer.Close();
            }
        }

        CloseBranchBlocks(nested);
    }

    private string CaseTest(BoundSelect select, VariableSymbol selector, BoundCaseClause clause)
    {
        // The runtime compares by the declared types of the selector and the clause value, as the operators do (ControlFlow golden).
        var mode = CompareModeName;
        var first = Convert(EmitExpression(clause.First), VbaType.Variant);
        var selectorVariant = DeclaredType(select.Value).IsVariant;
        var declaredFirst = DeclaredFlags(selectorVariant, DeclaredType(clause.First).IsVariant);
        return clause.Kind switch
        {
            CaseClauseKind.Value => $"{R}SelectCase.Matches({selector.EmitName}, {first}, {declaredFirst}, {mode})",
            CaseClauseKind.Range => $"{R}SelectCase.InRange({selector.EmitName}, {first}, {Convert(EmitExpression(clause.Second!), VbaType.Variant)}, {declaredFirst}, {DeclaredFlags(selectorVariant, DeclaredType(clause.Second!).IsVariant)}, {mode})",
            _ => $"{R}SelectCase.Compares({selector.EmitName}, {R}ComparisonOperator.{clause.Operator}, {first}, {declaredFirst}, {mode})",
        };
    }

    /// <summary>The type an expression was written with, under the conversion to Variant the binder wraps it in.</summary>
    private static VbaType DeclaredType(BoundExpression expression) =>
        expression is BoundConversion { Type.IsVariant: true, Operand: var operand } ? DeclaredType(operand) : expression.Type;

    private string CompareModeName => R + "CompareMode." + Symbol.Options.Compare;

    private void EmitFor(BoundFor forLoop)
    {
        var exit = new LoopExit(ExitKind.For, "__endFor" + (++temporaries).ToString(CultureInfo.InvariantCulture));
        loops.Push(exit);

        // The limit and step slots own their values (a string is copied) and the frame releases them, as for any Variant local (D20).
        var defaultStep = forLoop.Limit.Type.IsVariant ? new Emitted($"{VariantType}.FromInt16(1)", VbaType.Variant) : new Emitted($"(({forLoop.Limit.Type.CSharpName})1)", forLoop.Limit.Type);
        var step = forLoop.Step is null ? defaultStep : EmitExpression(forLoop.Step);
        EmitSimple(forLoop, Store(new BoundVariable(forLoop.Syntax, forLoop.Limit), EmitExpression(forLoop.To)) + ";");
        EmitSimple(forLoop, Store(new BoundVariable(forLoop.Syntax, forLoop.Increment), step) + ";");
        EmitSimple(forLoop, Store(forLoop.Counter, EmitExpression(forLoop.From)) + ";");

        string test;
        string increment;
        if (!forLoop.Limit.Type.IsVariant)
        {
            // A counter the runtime steps natively (ROADMAP.md D-J, M7 E): the limit and step slots have its type.
            var native = EmitExpression(forLoop.Counter).Code;
            test = $"{R}ForLoop.Continues({native}, {forLoop.Limit.EmitName}, {forLoop.Increment.EmitName})";
            increment = Store(forLoop.Counter, new Emitted($"{R}ForLoop.Next({native}, {forLoop.Increment.EmitName})", forLoop.Counter.Type));
        }
        else
        {
            var counter = Convert(EmitExpression(forLoop.Counter), VbaType.Variant);
            test = Inline(() => $"{R}ForLoop.Continues({counter}, {forLoop.Limit.EmitName}, {forLoop.Increment.EmitName})");
            var declared = DeclaredFlags(forLoop.Counter.Type.IsVariant, forLoop.Step?.Type.IsVariant ?? false);
            increment = Inline(() => Store(forLoop.Counter, new Emitted($"{R}Operators.Add({counter}, {forLoop.Increment.EmitName}, {declared})", VbaType.Variant)));
        }

        // The increment sits on the Next line so stepping visits Next, as it does in VBA.
        writer.MappedLine(Line(forLoop.Syntax), $"for (; {test};");
        writer.MappedLine(Line(forLoop.NextSyntax), $"    {increment})");
        writer.Open();
        EmitBlock(forLoop.Body);
        writer.Close();
        loops.Pop();
        if (exit.Used)
        {
            writer.HiddenLine($"{exit.Label}:;");
        }
    }

    private void EmitForEach(BoundForEach forEach)
    {
        var exit = new LoopExit(ExitKind.For, "__endFor" + (++temporaries).ToString(CultureInfo.InvariantCulture));
        loops.Push(exit);
        var enumerator = forEach.Enumerator.EmitName;
        EmitSimple(forEach, $"{enumerator} = {R}ForEachEnumerator.Create({Convert(EmitExpression(forEach.Collection), VbaType.Variant)}, __scope);");
        writer.MappedLine(Line(forEach.Syntax), $"while ({enumerator}.MoveNext())");
        writer.Open();
        EmitSimple(forEach, Store(forEach.Variable, new Emitted($"{enumerator}.Current", VbaType.Variant)) + ";");
        EmitBlock(forEach.Body);
        writer.Close();
        if (forEach.Variable.Type.IsVariant)
        {
            // After the last element of an array the loop variable is Empty (Arrays golden).
            writer.MappedLine(Line(forEach.NextSyntax), $"if ({enumerator}.IsArray) {Store(forEach.Variable, new Emitted($"{VariantType}.Empty", VbaType.Variant))};");
        }

        loops.Pop();
        if (exit.Used)
        {
            writer.HiddenLine($"{exit.Label}:;");
        }

        // What the enumerator held for the loop (a temporary array, a reference on the collection) goes with it, an Exit For included (D18).
        writer.HiddenLine($"{R}ObjectRefs.Release(ref {enumerator});");
    }

    private void EmitDoLoop(BoundDoLoop doLoop)
    {
        var exit = new LoopExit(ExitKind.Do, "__endDo" + (++temporaries).ToString(CultureInfo.InvariantCulture));
        loops.Push(exit);
        writer.MappedLine(Line(doLoop.Syntax), "while (true)");
        writer.Open();
        if (doLoop.TopCondition is not null)
        {
            EmitSimple(doLoop, $"if ({(doLoop.TopIsUntil ? string.Empty : "!")}{Condition(doLoop.TopCondition)}) break;");
        }

        EmitBlock(doLoop.Body);
        if (doLoop.BottomCondition is not null)
        {
            var condition = Condition(doLoop.BottomCondition);
            EmitSimple(LoopLine(doLoop), $"if ({(doLoop.BottomIsUntil ? string.Empty : "!")}{condition}) break;");
        }

        writer.Close();
        loops.Pop();
        if (exit.Used)
        {
            writer.HiddenLine($"{exit.Label}:;");
        }
    }

    /// <summary>The line of the Loop or Wend keyword, where a bottom condition is evaluated.</summary>
    private int LoopLine(BoundDoLoop doLoop) => doLoop.LoopSyntax switch
    {
        DoLoopBlockSyntax block => tree.GetLinePosition(block.LoopKeyword).Line,
        WhileBlockSyntax block => tree.GetLinePosition(block.WendKeyword).Line,
        var other => Line(other),
    };

    private sealed class LoopExit(ExitKind kind, string label)
    {
        public ExitKind Kind { get; } = kind;

        public string Label { get; } = label;

        public bool Used { get; set; }
    }
}
