namespace VbaNg.Compiler.Syntax;

/// <summary>
/// Kinds of trivia, tokens, and nodes. Keyword kinds cover every reserved identifier of
/// MS-VBAL 3.3.5.2; words the grammar quotes but does not reserve (Lib, Alias, PtrSafe, Explicit,
/// Base, Compare, Text, Binary, Step, Error, Name, Mid, Line, Width, Reset, Access, Append,
/// Output, Random, Read, Module, Object, Property, and so on) are identifiers that the parser
/// recognizes by text.
/// </summary>
public enum SyntaxKind : ushort
{
    None = 0,

    // Trivia (MS-VBAL 3.2.2, 3.3.1, 3.4).
    WhitespaceTrivia,
    CommentTrivia,
    LineContinuationTrivia,
    EndOfLineTrivia,
    ColonTrivia,
    ConditionalDirectiveTrivia,
    DisabledTextTrivia,
    SkippedTokensTrivia,

    // Tokens.
    EndOfFileToken,
    BadToken,
    IdentifierToken,
    ForeignNameToken,
    IntegerLiteralToken,
    FloatLiteralToken,
    StringLiteralToken,
    DateLiteralToken,
    HeaderLineToken,

    // Punctuation and operators (MS-VBAL 3.3.1 and 5.6).
    OpenParenToken,
    CloseParenToken,
    CommaToken,
    SemicolonToken,
    DotToken,
    BangToken,
    HashToken,
    EqualsToken,
    LessThanToken,
    GreaterThanToken,
    LessThanEqualsToken,
    GreaterThanEqualsToken,
    LessThanGreaterThanToken,
    PlusToken,
    MinusToken,
    AsteriskToken,
    SlashToken,
    BackslashToken,
    CaretToken,
    AmpersandToken,
    ColonToken,
    ColonEqualsToken,

    // Keywords: statement-keyword.
    CallKeyword,
    CaseKeyword,
    CloseKeyword,
    ConstKeyword,
    DeclareKeyword,
    DefBoolKeyword,
    DefByteKeyword,
    DefCurKeyword,
    DefDateKeyword,
    DefDblKeyword,
    DefIntKeyword,
    DefLngKeyword,
    DefLngLngKeyword,
    DefLngPtrKeyword,
    DefObjKeyword,
    DefSngKeyword,
    DefStrKeyword,
    DefVarKeyword,
    DimKeyword,
    DoKeyword,
    ElseKeyword,
    ElseIfKeyword,
    EndKeyword,
    EndIfKeyword,
    EnumKeyword,
    EraseKeyword,
    EventKeyword,
    ExitKeyword,
    ForKeyword,
    FriendKeyword,
    FunctionKeyword,
    GetKeyword,
    GlobalKeyword,
    GoSubKeyword,
    GoToKeyword,
    IfKeyword,
    ImplementsKeyword,
    InputKeyword,
    LetKeyword,
    LockKeyword,
    LoopKeyword,
    LSetKeyword,
    NextKeyword,
    OnKeyword,
    OpenKeyword,
    OptionKeyword,
    PrintKeyword,
    PrivateKeyword,
    PublicKeyword,
    PutKeyword,
    RaiseEventKeyword,
    ReDimKeyword,
    ResumeKeyword,
    ReturnKeyword,
    RSetKeyword,
    SeekKeyword,
    SelectKeyword,
    SetKeyword,
    StaticKeyword,
    StopKeyword,
    SubKeyword,
    TypeKeyword,
    UnlockKeyword,
    WendKeyword,
    WhileKeyword,
    WithKeyword,
    WriteKeyword,

    // Keywords: rem-keyword.
    RemKeyword,

    // Keywords: marker-keyword (Case, Else, Write, New are listed above or below).
    AnyKeyword,
    AsKeyword,
    ByRefKeyword,
    ByValKeyword,
    EachKeyword,
    InKeyword,
    NewKeyword,
    SharedKeyword,
    UntilKeyword,
    WithEventsKeyword,
    OptionalKeyword,
    ParamArrayKeyword,
    PreserveKeyword,
    SpcKeyword,
    TabKeyword,
    ThenKeyword,
    ToKeyword,

    // Keywords: operator-identifier (New is above).
    AddressOfKeyword,
    AndKeyword,
    EqvKeyword,
    ImpKeyword,
    IsKeyword,
    LikeKeyword,
    ModKeyword,
    NotKeyword,
    OrKeyword,
    TypeOfKeyword,
    XorKeyword,

    // Keywords: reserved-name.
    AbsKeyword,
    CBoolKeyword,
    CByteKeyword,
    CCurKeyword,
    CDateKeyword,
    CDblKeyword,
    CDecKeyword,
    CIntKeyword,
    CLngKeyword,
    CLngLngKeyword,
    CLngPtrKeyword,
    CSngKeyword,
    CStrKeyword,
    CVarKeyword,
    CVErrKeyword,
    DateKeyword,
    DebugKeyword,
    DoEventsKeyword,
    FixKeyword,
    IntKeyword,
    LenKeyword,
    LenBKeyword,
    MeKeyword,
    PSetKeyword,
    ScaleKeyword,
    SgnKeyword,
    StringKeyword,

    // Keywords: special-form (Input and Scale are above).
    ArrayKeyword,
    CircleKeyword,
    InputBKeyword,
    LBoundKeyword,
    UBoundKeyword,

    // Keywords: reserved-type-identifier (Date and String are above).
    BooleanKeyword,
    ByteKeyword,
    CurrencyKeyword,
    DoubleKeyword,
    IntegerKeyword,
    LongKeyword,
    LongLongKeyword,
    LongPtrKeyword,
    SingleKeyword,
    VariantKeyword,

    // Keywords: literal-identifier.
    TrueKeyword,
    FalseKeyword,
    NothingKeyword,
    EmptyKeyword,
    NullKeyword,

    // Keywords: reserved-for-implementation-use and future-reserved.
    AttributeKeyword,

    // Local is not in MS-VBAL 3.3.5.2, but the VBE reserves it: Dim Local is rejected and a procedure named Local stops the project compiling (docs/vba-quirks.md).
    LocalKeyword,
    CDeclKeyword,
    DecimalKeyword,
    DefDecKeyword,

    // Nodes: module structure (MS-VBAL 4.2, 5.1).
    Module,
    ModuleHeader,
    AttributeStatement,

    // Nodes: declarations (MS-VBAL 5.2).
    OptionStatement,
    DefTypeStatement,
    LetterRange,
    VariableDeclaration,
    VariableDeclarator,
    ConstDeclaration,
    ConstDeclarator,
    ArrayBounds,
    Bound,
    AsClause,
    ArrayDesignator,
    BuiltinType,
    NamedType,
    TypeDefinition,
    TypeMember,
    EnumDefinition,
    EnumMember,
    DeclareStatement,
    EventDeclaration,
    ImplementsStatement,

    // Nodes: procedures (MS-VBAL 5.3).
    ProcedureDeclaration,
    ParameterList,
    Parameter,
    EndBlockStatement,

    // Nodes: statements (MS-VBAL 5.4).
    BadStatement,
    LabelStatement,
    CallStatement,
    LetAssignmentStatement,
    SetAssignmentStatement,
    ReDimStatement,
    ReDimDeclarator,
    EraseStatement,
    MidStatement,
    LSetStatement,
    RSetStatement,
    IfBlock,
    ElseIfBlock,
    ElseBlock,
    SingleLineIfStatement,
    SingleLineElseClause,
    SelectCaseBlock,
    CaseBlock,
    ValueCaseClause,
    RangeCaseClause,
    IsCaseClause,
    ForBlock,
    StepClause,
    ForEachBlock,
    NextStatement,
    DoLoopBlock,
    WhileOrUntilClause,
    WhileBlock,
    WithBlock,
    GoToStatement,
    GoSubStatement,
    ReturnStatement,
    OnErrorStatement,
    OnGoToStatement,
    ResumeStatement,
    ErrorStatement,
    ExitStatement,
    EndStatement,
    StopStatement,
    RaiseEventStatement,
    NameStatement,
    OpenStatement,
    FileNumber,
    CloseStatement,
    ResetStatement,
    SeekStatement,
    LockStatement,
    RecordRange,
    LineInputStatement,
    WidthStatement,
    PrintStatement,
    WriteStatement,
    DebugPrintStatement,
    OutputItem,
    SpcClause,
    TabClause,
    InputStatement,
    PutStatement,
    GetStatement,

    // Nodes: expressions (MS-VBAL 5.6).
    LiteralExpression,
    IdentifierName,
    MemberAccessExpression,
    DictionaryAccessExpression,
    IndexExpression,
    ArgumentList,
    Argument,
    ParenthesizedExpression,
    UnaryExpression,
    BinaryExpression,
    NewExpression,
    TypeOfExpression,
    AddressOfExpression,
}
